CREATE TABLE SYMBOLS (
  ID INT NOT NULL,
  NAME VARCHAR(256)
);

CREATE TABLE STRATEGIES(
  ID INT NOT NULL,
  STRATEGY_NAME VARCHAR(256),
  STRATEGY_CLASS VARCHAR(256),
  CLASS_PARAMS VARCHAR(1024)
);

CREATE TABLE STRATEGIES_MAPPING(
  ID INT NOT NULL,
  STRATEGY_ID INT,
  MAPPED_ID INT,
  MAPPING_TYPE VARCHAR(256)
);

CREATE TABLE RISK_MANAGEMENT(
  ID INT NOT NULL,
  RISK_MANAGMENT_NAME VARCHAR(256),
  RISK_MANAGEMENT_CLASS VARCHAR(256),
  CLASS_PARAMS VARCHAR(1024)
);

CREATE TABLE RISK_MANAGEMENT_MAPPING(
  ID INT NOT NULL,
  RISK_MANAGEMENT_ID INT,
  MAPPED_ID INT,
  MAPPING_TYPE VARCHAR(256)
);


CREATE TABLE STOCKS_DATA(
  ID INT NOT NULL,
  STOCK_ID INT,
  LAST_STOCK_PRICE DOUBLE,
  ENTRY_PRICE DOUBLE,
  EXIT_PRICE DOUBLE,
  RANGE DOUBLE,
  POSITION_SIZE INT
);


