INSERT INTO SYMBOLS (ID,NAME)  VALUES (1,'JNUG');
INSERT INTO SYMBOLS (ID,NAME)  VALUES (2,'SPXU');
INSERT INTO SYMBOLS (ID,NAME)  VALUES (3,'TMV');
INSERT INTO SYMBOLS (ID,NAME)  VALUES (4,'USO');
INSERT INTO SYMBOLS (ID,NAME)  VALUES (5,'SPXL');
INSERT INTO SYMBOLS (ID,NAME)  VALUES (6,'YCS');

INSERT INTO STRATEGIES (ID,STRATEGY_NAME,STRATEGY_CLASS,CLASS_PARAMS) VALUES
  (1,'Short Term Turtle - Short','com.alon_gazit.strategy.ShortStrategy','numOfShortDays=40,numOfStopDays=20,numOfDaysForMovingAverage=100');
INSERT INTO STRATEGIES (ID,STRATEGY_NAME,STRATEGY_CLASS,CLASS_PARAMS) VALUES
  (2,'Short Term Turtle - Long','com.alon_gazit.strategy.LongStrategy','numOfLongDays=40,numOfStopDays=20,numOfDaysForMovingAverage=100');
INSERT INTO STRATEGIES (ID,STRATEGY_NAME,STRATEGY_CLASS,CLASS_PARAMS) VALUES
  (3,'Long Term Turtle - Short','com.alon_gazit.strategy.ShortStrategy','numOfShortDays=100,numOfStopDays=50,numOfDaysForMovingAverage=200');
INSERT INTO STRATEGIES (ID,STRATEGY_NAME,STRATEGY_CLASS,CLASS_PARAMS) VALUES
  (4,'Long Term Turtle - Long','com.alon_gazit.strategy.LongStrategy','numOfLongDays=100,numOfStopDays=50,numOfDaysForMovingAverage=200');
INSERT INTO STRATEGIES (ID,STRATEGY_NAME,STRATEGY_CLASS,CLASS_PARAMS) VALUES
  (5,'Short Term Turtle',NULL ,NULL);
INSERT INTO STRATEGIES (ID,STRATEGY_NAME,STRATEGY_CLASS,CLASS_PARAMS) VALUES
  (6,'Long Term Turtle',NULL,NULL);

INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (1,1,1,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (2,1,2,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (3,1,3,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (4,1,4,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (5,1,5,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (6,1,6,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (7,2,1,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (8,2,2,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (9,2,3,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (10,2,4,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (11,2,5,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (12,2,6,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (13,3,1,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (14,3,2,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (15,3,3,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (16,3,4,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (17,3,5,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (18,3,6,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (19,4,1,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (20,4,2,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (21,4,3,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (22,4,4,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (23,4,5,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (24,4,6,'INVESTMENT_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (25,5,1,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (26,5,2,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (27,5,3,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (28,5,4,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (29,5,5,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (30,5,6,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (31,5,7,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (32,5,8,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (33,5,9,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (34,5,10,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (35,5,11,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (36,5,12,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (37,6,13,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (38,6,14,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (39,6,15,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (40,6,16,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (41,6,17,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (42,6,18,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (43,6,19,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (44,6,20,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (45,6,21,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (46,6,22,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (47,6,23,'COMBINED_TYPE');
INSERT INTO STRATEGIES_MAPPING (ID,STRATEGY_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (48,6,24,'COMBINED_TYPE');

INSERT INTO RISK_MANAGEMENT (ID,RISK_MANAGMENT_NAME,RISK_MANAGEMENT_CLASS,CLASS_PARAMS) VALUES
  (1,'Basic Risk Management','com.alon_gazit.risk.BasicRiskManagement','');

INSERT INTO RISK_MANAGEMENT_MAPPING (ID,RISK_MANAGEMENT_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (1,1,1,'INVESTMENT_TYPE');
INSERT INTO RISK_MANAGEMENT_MAPPING (ID,RISK_MANAGEMENT_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (2,1,2,'INVESTMENT_TYPE');
INSERT INTO RISK_MANAGEMENT_MAPPING (ID,RISK_MANAGEMENT_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (3,1,3,'INVESTMENT_TYPE');
INSERT INTO RISK_MANAGEMENT_MAPPING (ID,RISK_MANAGEMENT_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (4,1,4,'INVESTMENT_TYPE');
INSERT INTO RISK_MANAGEMENT_MAPPING (ID,RISK_MANAGEMENT_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (5,1,5,'INVESTMENT_TYPE');
INSERT INTO RISK_MANAGEMENT_MAPPING (ID,RISK_MANAGEMENT_ID,MAPPED_ID,MAPPING_TYPE) VALUES
  (6,1,6,'INVESTMENT_TYPE');


